### ISSUE TITLE
Remove XSS issues when requesting cart status information

### ISSUE THREAD

**Issue by kauberry** [EMSL-MSC/pacifica-upload-status#12]
Getting errors back from the main server like...

    XMLHttpRequest cannot load
    https://blah.my.emsl.pnl.gov/myemsl/api/2/cart/
    No 'Access-Control-Allow-Origin' header is present on the requested
    resource. Origin 'https://status.my.emsl.pnl.gov' is therefore
    not allowed access.

Need to add appropriate headers to Ajax endpoints to make this ok

**Comment by dmlb2000** [comment]
This is a duplicate of #10
