### ISSUE TITLE
Sort status

### ISSUE THREAD

**Issue by casey-pnnl** [EMSL-MSC/pacifica-upload-status#133]
@kauberry 

Is it possible to sort the results returned from the metadata server? The status tool is returning a list of seemingly unsorted items. 

For example, we are getting results with instrument ID as follows:
10004
10005
10006
10007
10000
10001
10002
10003
10008

**Comment by kauberry** [comment]
Hi Casey,

The status tool is supposed to sort things by descending upload time. If it’s not, we can dig deeper into it.


Thanks,
Ken


Ken J. Auberry, <mailto:Kenneth.Auberry@pnnl.gov> Senior Research Scientist
Instrument Development Laboratory
Environmental Molecular Sciences Laboratory<http://www.emsl.pnnl.gov/>
email: Kenneth.Auberry@pnnl.gov<mailto:Kenneth.Auberry@pnnl.gov>
tel: 509.371.6442 <tel:+1-509-371-6442>




On Jul 21, 2017, at 4:25 PM, casey-pnnl <notifications@github.com<mailto:notifications@github.com>> wrote:


@kauberry<https://github.com/kauberry>

Is it possible to sort the results returned from the metadata server? The status tool is returning a list of seemingly unsorted items.

For example, we are getting results with instrument ID as follows:
10004
10005
10006
10007
10000
10001
10002
10003
10008

**Comment by casey-pnnl** [comment]
Ok, that's good. Is that also the case for the query-building dropdowns, before the results are displayed?

I noticed this behavior in the report-building dropdown, not the results themselves. This isn't a major problem, just curious if there's something we've missed.

![2017-07-21-pacifica-status-screenshot](https://user-images.githubusercontent.com/9203588/28486261-63247b34-6e35-11e7-8f8f-9aaa5da7842b.PNG)


Thanks,
Casey

**Comment by kauberry** [comment]
Sorry, misunderstood what data you were referring to. Theoretically, the instruments should be sorted by instrument ID. Not sure why yours aren’t.


Thanks,
Ken


Ken J. Auberry, <mailto:Kenneth.Auberry@pnnl.gov> Senior Research Scientist
Instrument Development Laboratory
Environmental Molecular Sciences Laboratory<http://www.emsl.pnnl.gov/>
email: Kenneth.Auberry@pnnl.gov<mailto:Kenneth.Auberry@pnnl.gov>
tel: 509.371.6442 <tel:+1-509-371-6442>




On Jul 21, 2017, at 4:56 PM, casey-pnnl <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, that's good. Is that also the case for the query-building dropdowns, before the results are displayed?

I noticed this behavior in the report-building dropdown, not the results themselves. This isn't a major problem, just curious if there's something we've missed.

[2017-07-21-pacifica-status-screenshot]<https://user-images.githubusercontent.com/9203588/28486261-63247b34-6e35-11e7-8f8f-9aaa5da7842b.PNG>

Thanks,
Casey
