### ISSUE TITLE
Database Config Code Copy

### ISSUE THREAD

**Issue by dmlb2000** [EMSL-MSC/pacifica-upload-status#33]
There is a copy of the database configuration in the `libraries/EUS.php` from the config version `config/database.php` we should try to load the default config in EUS and change just the prefix in `EUS.php`

**Comment by dmlb2000** [comment]
I maybe reading that wrong... the constructor for `class EUS` in `EUS.php` has a copy of the database config in it, that's static, should that copy be needed?

We could also do something like in the pull request, copy default db config to eus_for_myemsl then just change the `dbprefix`

**Comment by kauberry** [comment]
I think it was like that because the EUS library could also be used independently of the MyEMSL stack. It should most likely be an either/or proposition, so it should be revisited. 

---- 
Ken J. Auberry 
email: kauberry@mac.com

**Comment by dmlb2000** [comment]
Yeah, when we start refactoring this to work with the refactored code base this will need to be merged in with a more unified model. There will still need to be two models potentially, one for status website preferences (if there ever becomes such a thing) and the metadata services models.
