### ISSUE TITLE
Why does the database configuration have postgres specific configs?

### ISSUE THREAD

**Issue by dmlb2000** [EMSL-MSC/pacifica-upload-status#84]
in the `application/config/database.php` configuration the following lines don't seem to be needed. Can we remove them?

```
$db['init_postgres'] = $db['default'];
$db['init_postgres']['database'] = 'postgres';

$db['eus_for_myemsl'] = $db['default'];
$db['eus_for_myemsl']['dbprefix'] = 'eus.';

$db['website_prefs'] = $db['default'];
$db['website_prefs']['dbprefix'] = 'website_prefs.';
```

**Comment by kauberry** [comment]
I don't need those last two blocks, but I need to be able to hit an instance that I know exists by default so that I can connect to it to create the uploader status database instance.

**Comment by kauberry** [comment]
I'm going to change this configuration based on the conversation that we had regarding database instance creation that occurs during deployment.
